"""removed check notifications'

Revision ID: aaa557662da0
Revises: cb334b349ae9
Create Date: 2022-12-06 13:39:17.018450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa557662da0'
down_revision = 'cb334b349ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'timestamp')
    op.drop_column('likes', 'timestamp')
    op.drop_column('user', 'last_notification_checked_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notification_checked_time', sa.DATETIME(), nullable=True))
    op.add_column('likes', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('followers', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
