"""check notifications

Revision ID: cb334b349ae9
Revises: e3b119fe89b2
Create Date: 2022-12-06 12:59:10.181441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb334b349ae9'
down_revision = 'e3b119fe89b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('likes', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_notification_checked_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_notification_checked_time')
    op.drop_column('likes', 'timestamp')
    op.drop_column('followers', 'timestamp')
    # ### end Alembic commands ###
